### ISSUE TITLE
Ancient sceptre not recognized as magic weapon

### ISSUE THREAD

**Issue by ZeiZeiii** [BraveH/gear-switch-alert#1]

**Comment by BraveH** [comment]
Is it still not recognizing it as magic when you set the combat style to spell? The way the plugin works is that if you have an ancient staff or sceptre (or any other magical staff) but are using it as a melee weapon for some reason by not specifying the right attack style it will show it as a melee gear. However as soon as you change combat style to spell it will show the weapon as a magic weapon...

![image](https://github.com/BraveH/gear-switch-alert/assets/1398714/f7483cae-7435-4728-aa09-2770fb3e32aa)
![image](https://github.com/BraveH/gear-switch-alert/assets/1398714/bb62a0aa-e68c-4dac-82db-0ada852d6823)

====================

![image](https://github.com/BraveH/gear-switch-alert/assets/1398714/c97a43e0-8729-4c09-9ab3-74a8298ada63)
![image](https://github.com/BraveH/gear-switch-alert/assets/1398714/ae2c3346-a2f7-4a39-8280-90c502e27aa3)

**Comment by ZeiZeiii** [comment]
That solves the problem, thank you!
