### ISSUE TITLE
Staff long range tagged as melee

### ISSUE THREAD

**Issue by Tiezhcial** [BraveH/gear-switch-alert#11]
Using the Trident of the Swamp on long range tags melee gear.

**Comment by Abyssalsol** [comment]
Having this same issue with the shadow and sanguinesti staff. Will tag melee gear on long-range like you have nothing equipped or a melee weapon. Happened around colosseum release.

**Comment by jboss94** [comment]
having the same issue

**Comment by dustofff** [comment]
This issue is persisting for me as well, how do I apply the fix?

**Comment by daltonpearson** [comment]
Just submitted a [PR](https://github.com/BraveH/gear-switch-alert/pull/13) which fixes this issue.
