### ISSUE TITLE
Plugin became incompatible after 8/14/2024 update

### ISSUE THREAD

**Issue by Ayybel** [BraveH/gear-switch-alert#17]
The Dynamic Inventory Tag plugin has broken as of the August 14, 2024 Runelite/game update.

**Comment by Archadon** [comment]
As of August 21, 2024, plugin still is broken. I am unsure what the pull request from above is, but if it would result in a fix to it, that would be fantastic. This quickly became one of my favorite plugins before it broke, and would like to keep using it.
