### ISSUE TITLE
Transfer Ownership To Active Developer

### ISSUE THREAD

**Issue by cjfritz9** [BraveH/gear-switch-alert#24]
It's past time to transfer ownership of this plugin to the @daltonpearson. It's a great plugin and the only people maintaining it are not the original developer, @BraveH - whose last commit is over a year ago and the most active support is always from @daltonpearson.

I've seen him offer to take it over in an issue and I think everyone would be happier if that were the case.

**Comment by BraveH** [comment]
Added him so now he can accept. Closing
