### ISSUE TITLE
Tags only working on melee items

### ISSUE THREAD

**Issue by notWakeful** [BraveH/gear-switch-alert#4]
I can get the tags to work as normal on all melee items such as whips, daggers, rapier, barrows gloves, etc., but when it comes to all mage and ranged items the tags will not show up. The items themselves will also say that they are tagged, but still the outline color does not show. I have tried uninstalling and reinstalling the plug in multiple times. Just have not been able to find a fix mentioned anywhere.

**Comment by BraveH** [comment]
@notWakeful  Hey, so the items only get tagged when you equip the weapon relating to their weapon style first. It’s meant to remind you of fear switches that are missing. Have you equipped a ranged weapon and the tags still won’t show around the rest of the “ranged-tagged” items in your inventory?

If so, can you please share some screenshots so I can try to understand what’s going wrong?

**Comment by notWakeful** [comment]
@BraveH that was it! Thank you so much for the response. Have a good one!
