### ISSUE TITLE
Plugin is incompatible

### ISSUE THREAD

**Issue by scv-m** [BraveH/gear-switch-alert#5]
Plugin hub is showing "Plugin is incompatible and requires its author to update it."

![image](https://github.com/BraveH/gear-switch-alert/assets/965541/eef2f8ef-0df8-4390-aa5d-35c5e116876a)

**Comment by BraveH** [comment]
https://github.com/runelite/plugin-hub/pull/4911 closes this issue

**Comment by cmartinmooney** [comment]
This is wildly embarrassing- but how do i actually do that? <3

**Comment by BraveH** [comment]
@cmartinmooney nothing for you to do really. That link I posted needs to be approved by the runelite devs and once it is approved and added to their code the plugin will continue to work again.

**Comment by raiyni** [comment]
what is this? [`0cac95c6937e0c3fb29e45d50e73e57042a2c347...BraveH:06f6240ee9bfbeaeb96490309dbf2b825cd90707`#diff-fd35dcdaae](https://github.com/BraveH/gear-switch-alert/compare/0cac95c6937e0c3fb29e45d50e73e57042a2c347...BraveH:06f6240ee9bfbeaeb96490309dbf2b825cd90707#diff-fd35dcdaaeb319375854c95e0c218890e506ac8b043d5eac7759571479f0ecc0R12)

**Comment by BraveH** [comment]
> what is this? [`0cac95c6937e0c3fb29e45d50e73e57042a2c347...BraveH:06f6240ee9bfbeaeb96490309dbf2b825cd90707`#diff-fd35dcdaae](https://github.com/BraveH/gear-switch-alert/compare/0cac95c6937e0c3fb29e45d50e73e57042a2c347...BraveH:06f6240ee9bfbeaeb96490309dbf2b825cd90707#diff-fd35dcdaaeb319375854c95e0c218890e506ac8b043d5eac7759571479f0ecc0R12)

Oh yea thanks for the find, I forgot to remove that from the test file. I was just trying to write plugins to solve the minipuzzles for the zebak and akkha puzzle rooms but i failed miserably so I stopped. And then found out other plugins that make life easier there anyways lol

**Comment by raiyni** [comment]
You left the imports in.

**Comment by aLatif01** [comment]
I miss your plugin, can we fix? :(

**Comment by BraveH** [comment]
@raiyni thanks again, removed the import but runelite staff hasn't seen the PR yet anyways so still stuck on their approval.

@aLatif01  Still waiting for plugin approval, all up to runelite team really...

**Comment by aLatif01** [comment]
@BraveH got it, goodluck hopefully approved soon! 😄

**Comment by anthony4987** [comment]
I don't recall other plugins taking this long update, is there anything we can do?

**Comment by BraveH** [comment]
@raiyni Can you help merging the update?

**Comment by BraveH** [comment]
Changes merged and is fixed now!
