### ISSUE TITLE
Mislabeling

### ISSUE THREAD

**Issue by cmartinmooney** [BraveH/gear-switch-alert#7]
My dynamic tags has been registering BGS as a mage weapon and swamp  trident as a melee weapon.
I've gone through front end settings and re-install, but the issue persists. Began yesterday after Varlamore update.

**Comment by aLatif01** [comment]
+1

**Comment by BraveH** [comment]
I'm having a look at it now. Will try to see why yesterday's update messed up some stuff.

**Comment by BraveH** [comment]
Solved

**Comment by cmartinmooney** [comment]
ilysm, if i see you irl you get a kwiss

**Comment by BraveH** [comment]
still not approved on runelite git: https://github.com/runelite/plugin-hub/pull/5736

**Comment by cmartinmooney** [comment]
bless you, apologies!
