### ISSUE TITLE
Mage Switch Issues

### ISSUE THREAD

**Issue by daleric-xyz** [BraveH/gear-switch-alert#8]
Hi there,

Currently, if I equip my shadow it doesn't seem to register that I have a mage weapon equipped, and leaves my mage gear as not being highlighted.
My range and melee setups still work though.

Anything I am missing?

Here's my current profile - 
![image](https://github.com/BraveH/gear-switch-alert/assets/58330127/030561db-c744-4881-bbcd-77c524184089)

**Comment by dowodenum** [comment]
Someone in my clan is trying to troubleshoot this right now, came here and saw this, so it's not just you at least.

**Comment by BraveH** [comment]
I'm having a look at it now. Will try to see why yesterday's update messed up some stuff.

**Comment by BraveH** [comment]
Solved

**Comment by daleric-xyz** [comment]
Has the update been pushed? It's still not working for me.

**Comment by BraveH** [comment]
still not approved on runelite git: https://github.com/runelite/plugin-hub/pull/5736

**Comment by dustofff** [comment]
I'm having this same issue, has this been fixed yet?
